### PR TITLE
Upgrade to boringtun 0.5

### PR DESCRIPTION
**Pull request by mhils**

### CODE REVIEW

**Comment by decathorpe** [comment]
Looks good to me! Also nice to see that the clippy run from CI can add annotations to the PR.

Do you think it would make sense to merge the test client into the Python module as something like `mitmproxy_wireguard.run_echo_test_client()`? That would allow us to ship it with the mitmproxy_wireguard Python package.

That won't work for `echo_test_server.py`. Where did you want to put this code to be able to run tests for the mitmproxy server? Depending on whether it should be in mitmproxy_wireguard or in the mitmproxy test code itself, it could receive the same treatment (but I'd need to rewrite it in Rust first).

**Comment by mhils** [comment]
> Do you think it would make sense to merge the test client into the Python module as something like `mitmproxy_wireguard.run_echo_test_client()`? That would allow us to ship it with the mitmproxy_wireguard Python package.

What's the benefit? Seems like that only increases binary wheel size for users. I'd be perfectly fine with putting the binary into test/ in mitmproxy/mitmproxy.

> That won't work for echo_test_server.py. Where did you want to put this code to be able to run tests for the mitmproxy server? 

I don't think we want/need `echo_test_server.py` at all for the tests. I thought we could write a Python test (in mitmproxy/mitmproxy) where we monkeypatch `ProxyConnectionHandler` with a minimal echo server and then just instantiate `WireGuardServerInstance` and `.start()` it? That should yield full coverage for `WireGuardServerInstance.handle_tcp_connection` and `WireGuardServerInstance.handle_udp_datagram`. Does that make sense?

**Comment by decathorpe** [comment]
> What's the benefit? Seems like that only increases binary wheel size for users. I'd be perfectly fine with putting the binary into test/ in mitmproxy/mitmproxy.

Well, the benefit would be that it would always be up-to-date, and built on all supported architectures / targets. Just building it once would mean it's only included in a static version for one architecture / target (probably x86_64-unknown-linux-gnu) and wouldn't be available for running tests on other architectures.

**Comment by decathorpe** [comment]
> What's the benefit? Seems like that only increases binary wheel size for users. I'd be perfectly fine with putting the binary into test/ in mitmproxy/mitmproxy.

Just out of curiosity, I compared the size of `mitmproxy_wireguard.abi3.so` before and after merging `run_test_client` function. The size increased by a mere 1.4% (51 KB) from ~3.58 MB to ~3.63 MB. That's not so bad, and it makes shipping the compiled test client code much simpler.

> I don't think we want/need `echo_test_server.py` at all for the tests. I thought we could write a Python test (in mitmproxy/mitmproxy) where we monkeypatch `ProxyConnectionHandler` with a minimal echo server and then just instantiate `WireGuardServerInstance` and `.start()` it? That should yield full coverage for `WireGuardServerInstance.handle_tcp_connection` and `WireGuardServerInstance.handle_udp_datagram`. Does that make sense?

If that works, then that sounds good.

**Pull request merged**
