### PR TITLE
Simplify CI

### PR DESCRIPTION
**Pull request by mhils**
This PR simplifies our CI setup and hardens it against supply chain attacks:

 - Most importantly, all third-party actions are removed. We shouldn't use those as they introduce unnecessary supply chain risk unless pinned and audited. 
 - We now pin `maturin` and install `twine` via apt.
 - To simplify Linux builds, we now use zig for manylinux-compatible compilation.

I've also taken the liberty to switch `rustfmt` to stable without any custom settings, which makes the CI setup easier and looks just as good to me. Feel free to revert this change and judge me for it, I don't have particular opinions other than a slight preference for the most simple approach.

### CODE REVIEW

**Comment by decathorpe** [comment]
- Which version of rust/cargo will be used after this change? It looks like we'll lose control over that with this approach (i.e. we can't explicitly say "latest stable" or "1.56.0" or "nightly"). It looks like `rustup` is available in the default containers though?
- Are *all* of the settings in the current `rustfmt.toml` unstable, or are some of them also accepted by stable rustfmt? I use the same settings for all my Rust projects, and I'd like to keep at least the ones that are available on stable Rust.
- The `maturin[zig]` feature is marked as experimental, does it actually produce binaries that work?
- Looks like you're no longer building the test client binary on aarch64-apple-darwin, is this intentional?
- Why are you setting `--manylinux 2014` explicitly? `maturin` automatically chooses the oldest manylinux version that the wheel is compatible with (for x86_64/linux, that's manylinux 2010 right now, and for aarch64/linux, it's manylinux 2014, possibly because Rust needs a newer glibc on aarch64).
- Will we lose Pull Request annotations by invoking `cargo check` / `cargo clippy` directly or will those still work?

**Comment by mhils** [comment]
> * Which version of rust/cargo will be used after this change? It looks like we'll lose control over that with this approach (i.e. we can't explicitly say "latest stable" or "1.56.0" or "nightly"). It looks like `rustup` is available in the default containers though?

We use whatever GitHub Actions ships with by default (a current or at least recent stable release). If you would want a more specific version you could call rustup, but I think the default is just fine for us.

> * Are _all_ of the settings in the current `rustfmt.toml` unstable, or are some of them also accepted by stable rustfmt? I use the same settings for all my Rust projects, and I'd like to keep at least the ones that are available on stable Rust.

If you have strong preferences here we can just restore `rustfmt.toml` and do `cargo +nightly fmt`. I also use the same settings for all my Rust projects (i.e. not configuring anything at all). Let's do either of those, but not compromise in the middle. Again, other people tend to have stronger feelings about this than I do so feel free to revert. 😉 

> * The `maturin[zig]` feature is marked as experimental, does it actually produce binaries that work?

Yes. The produced x64 binary + wheel seem to work just fine. :)

> * Looks like you're no longer building the test client binary on aarch64-apple-darwin, is this intentional?

I think macOS M1 users can run x64 binaries anyways, so I figured there's no point really.

> * Why are you setting `--manylinux 2014` explicitly? `maturin` automatically chooses the oldest manylinux version that the wheel is compatible with (for x86_64/linux, that's manylinux 2010 right now, and for aarch64/linux, it's manylinux 2014, possibly because Rust needs a newer glibc on aarch64).

Setting this explicitly makes maturin error if the binaries are not manylinux2014. Supporting anything below 2014 does not make much sense, we have other dependencies (e.g. cryptography) that don't support that either.

> * Will we lose Pull Request annotations by invoking `cargo check` / `cargo clippy` directly or will those still work?

Ah, seems like that's something that's actually useful. Restored.

**Comment by decathorpe** [comment]
Thanks, looks good to me. I don't have strong opinion on the rustfmt thing either, so "stable rustfmt with no custom settings" works for me too.

> We use whatever GitHub Actions ships with by default (a current or at least recent stable release). If you would want a more specific version you could call rustup, but I think the default is just fine for us.

This would probably only make sense to check whether we still support the oldest Rust version we claim to support, but that's something that can easily be added in the future.

**Comment by decathorpe** [comment]
Now let's see if the "publish" action still works :)

**Pull request merged**
