### PR TITLE
ci: run `apt-get update`

### PR DESCRIPTION
**Pull request by mhils**
Just recalled we also need to do this. :)

### CODE REVIEW

**Comment by decathorpe** [comment]
Would it make sense to also run this in the "ci" action?

**Comment by mhils** [comment]
There are no apt installs there, no?

**Comment by decathorpe** [comment]
True, but it would probably be good to update the available Rust toolchain? Looking at the logs, rustup doesn't install the latest toolchain, so the CI action uses whatever /usr/bin/cargo is available in the container :(

**Comment by mhils** [comment]
The problem with `apt-get install` is that it fails if you don't `apt-get update` before. So doing that is necessary. cargo should work fine with either the preinstalled or an updated toolchain (so doing that is not necessary).

> so the CI action uses whatever /usr/bin/cargo is available in the container

My take on this would be that whatever the container provides is recent enough, and just using what is already there is easiest. If you prefer to run rustup before, that's fine with me as well. :)

**Comment by decathorpe** [comment]
> The problem with apt-get install is that it fails if you don't apt-get update before.

I don't think it does? It ran fine when publishing 0.1.9:
https://github.com/decathorpe/mitmproxy_wireguard/actions/runs/3081309297/jobs/4979802621

But either way, looks fine to me.

**Comment by mhils** [comment]
> I don't think it does? It ran fine when publishing 0.1.9: https://github.com/decathorpe/mitmproxy_wireguard/actions/runs/3081309297/jobs/4979802621

Most of the times it works... but https://docs.github.com/en/actions/using-github-hosted-runners/customizing-github-hosted-runners#installing-software-on-ubuntu-runners (we've been bitten by this before)

**Pull request merged**
