### PR TITLE
Fix panic for too large packets

### PR DESCRIPTION
**Pull request by mhils**
See https://github.com/mitmproxy/mitmproxy/issues/5592#issuecomment-1292141069 😃 

*Edit: With rustfmt complaining again I've also added an autofix.ci job. You may need to install the GitHub App for that.* 🙃

### CODE REVIEW

**Comment by decathorpe** [comment]
I dropped the autofix action (rustfmt could be a pre-commit hook, no need to make this a GitHub action), and clippy has false positives and "clippy --fix" can't fix all problems that are reported by clippy anyway.

I also changed the check to `MAX_PACKET_SIZE - 80` instead of `MAX_PACKET_SIZE - 60` because while WireGuard headers for IPv4 are 60 bytes, they are 80 bytes for IPv6.

**Comment by mhils** [comment]
> rustfmt could be a pre-commit hook, no need to make this a GitHub action

pre-commit hooks don't solve the problem here very well because my local toolchain regularly does not have the same rustfmt version (this was the case here). Fighting CI for this is slightly annoying to put it mildly.

If pre-commit hooks would work so well, we could ditch the `--check` job entirely. I have fought this battle too often, auto-fixing is considerably more practical from my experience. But I will let you make that experience yourself if you want. :)

**Comment by decathorpe** [comment]
That's weird, rustfmt output should be stable between versions, except for when nightly rustfmt supports more options, which are ignored by other versions.

**Comment by mhils** [comment]
I updated my (rather outdated) stable toolchain and then it worked. 🤷

**Pull request closed without merging**
