### PR TITLE
cargo: update MSRV from 1.56.0 to 1.58.0 and add checks for it in CI

### PR DESCRIPTION
**Pull request by decathorpe**

### CODE REVIEW

**Review by mhils — COMMENTED** [review]
Can you explain to me what we are trying to achieve here?
GitHub Actions' best practice workflow template is really just [`cargo build` followed by `cargo test`](https://github.com/mitmproxy/mitmproxy/new/main?filename=.github%2Fworkflows%2Frust.yml&workflow_template=rust).  The runner image (and what it ships with) is fully documented at [actions/runner-images](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md). Is there any reason why it would be terribly wrong to use the preinstalled toolchain?

Apart from that, I'm not sure why one would want to run `cargo check` first. From my perspective that adds 80s of CI runtime and masks subsequent errors, which is kind of annoying. I see that it makes perfect sense for _libraries_ to declare a MSRV and the religiously test that, but that's not really the situation we are in. Is there some benefit to this I'm overlooking?

**Comment by decathorpe** [comment]
> Can you explain to me what we are trying to achieve here?

I am trying to make the CI and publish actions have consistent results, since I don't "trust" the ubuntu-latest container to always have the Rust toolchain I want.

> GitHub Actions' best practice workflow template is really just `cargo build` followed by `cargo test`.

The only reason to split this into two steps is to make it more visible in the GitHub UI which particular step (i.e. `build` or `test`) failed, but `cargo test` itself would be enough, as it also builds the project if it wasn't built already.

> The runner image (and what it ships with) is fully documented at [actions/runner-images](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md). Is there any reason why it would be terribly wrong to use the preinstalled toolchain?

Not terribly wrong, but using rustup ensures that we get the official Rust toolchain, not "whatever the GitHub container has pre-installed".

> Apart from that, I'm not sure why one would want to run `cargo check` first.

Same reason why `cargo build` and `cargo test` are separate steps above? :)

> From my perspective that adds 80s of CI runtime and masks subsequent errors, which is kind of annoying.

No, it doesn't mask any errors at all. If `cargo check` fails, there's something seriously wrong (i.e. early-stage compiler errors, like syntax errors, mismatched types, etc.), and there's no reason to run either `cargo test` or `cargo clippy`, because both of these steps would fail with the same compiler error that `cargo check` already failed with.

I can merge the `cargo check` step the `cargo test` job as a separate step, and have `clippy` run regardless? That should resolve the "80 seconds of additional CI runtime" problem, at least ... but it will make `clippy` needlessly fail if there's `cargo check` failures.

> I see that it makes perfect sense for _libraries_ to declare a MSRV and the religiously test that, but that's not really the situation we are in. Is there some benefit to this I'm overlooking?

The benefit would be for other contributors rather than for users. Getting cryptic error messages (something like "cannot find matching version for console-subscriber =0.1.8") because your local Rust toolchain is too old is really bad developer experience, and specifying a correct (or at least somewhere between "correct" and "recent enough") MSRV avoids this kind of problem.

**Comment by mhils** [comment]
> I am trying to make the CI and publish actions have consistent results, since I don't "trust" the ubuntu-latest container to always have the Rust toolchain I want.

I think my point was to encourage you to trust those[^1], but if you still feel better with the rustup version that is fine with me as well. :)

[^1]: Technically we're depending on even fewer third parties, but trusting rustup is reasonable I guess. 😉 

> I can merge the `cargo check` step the `cargo test` job as a separate step, and have `clippy` run regardless? That should resolve the "80 seconds of additional CI runtime" problem, at least ... but it will make `clippy` needlessly fail if there's `cargo check` failures.

I personally would just ditch `cargo check` entirely, if you push code that does not even compile you kind of deserve it. 😛 
But jokes aside: My only real issue here is the increase in CI time, which is easily fixed by not making the jobs depend on each other. 👍 

> The benefit would be for other contributors rather than for users. Getting cryptic error messages (something like "cannot find matching version for console-subscriber =0.1.8") because your local Rust toolchain is too old is really bad developer experience, and specifying a correct (or at least somewhere between "correct" and "recent enough") MSRV avoids this kind of problem.

Yeah, that's a fair point. As long as we mercilessly update `rust-version` to the latest stable if we have the need I'm happy with this.

**Comment by decathorpe** [comment]
> I think my point was to encourage you to trust those[1](#user-content-fn-1-a8e5e4660a574f6cdb97f98d5cab1353), but if you still feel better with the rustup version that is fine with me as well. :)

Looking at the docs for the ubuntu-latest container, they already use rustup to install the Rust toolchain[^1], so the only thing this change does is enforce "latest stable" when running CI, which might not have propagated to the container images yet. I'm not sure what the delay between Rust releases and refreshed GitHub container images is, so I'd like to keep the "always use latest stable Rust" steps, especially for the `publish` action, where having latest stable Rust is even more important (mostly for compiler bugfixes, and performance optimizations due to codegen improvements or standard library changes[^2]).

> I personally would just ditch `cargo check` entirely, if you push code that does not even compile you kind of deserve it. stuck_out_tongue But jokes aside: My only real issue here is the increase in CI time, which is easily fixed by not making the jobs depend on each other. +1

I'd like to keep it as a separate step so it's more obvious that things failed at an early stage and not when running actual tests. But I merged the `cargo check` call into the `cargo test` job, so the dependency is gone, does that look good to you?

> Yeah, that's a fair point. As long as we mercilessly update `rust-version` to the latest stable if we have the need I'm happy with this.

Yeah, that was my intention. I'd like to keep the `rust-version` setting in `Cargo.toml` reasonably up-to-date, but of course increasing MSRV is not a breaking change for `mitmproxy_wireguard`, so it can be done very liberally. Testing whether MSRV is still accurate would be possible to do manually, but that would be an additional checklist item before tagging a release ... and having the check in CI would mean problems with it are caught early and can't be forgotten.

[^1]: https://github.com/actions/runner-images/blob/main/images/linux/scripts/installers/rust.sh
[^2]: https://blog.rust-lang.org/2022/09/22/Rust-1.64.0.html#compatibility-notes

**Review by mhils — APPROVED** [review]
Looks good!

**Pull request merged**
